---
title: "Tensor_emprical2"
output: html_document
date: "2023-01-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 读取数据  

```{r}
library("readr")
rawdata <- readr::read_csv("tensor.csv", col_names = FALSE, col_types = cols(X1 = col_date(format = "%Y%m")),skip = 16)
rawdata <- rawdata[1:(nrow(rawdata) - 1), ] # remove NA rows
rawdata <- as.data.frame(rawdata)
attrdata <- read.csv("tensor.csv", header = FALSE, skip=15,nrows = 1)
header <- c("date", unlist(attrdata[1,2:ncol(attrdata)]))
colnames(rawdata) <- header

data<-rawdata[451:1156,]
rownames(data) <- 1:nrow(data)
data[,2:ncol(data)]<-as.numeric(unlist(data[,2:ncol(data)]))
```

```{r}
#缺失值改变记号
data1<-data[,-1]
summary(data1)
for(i in 1:nrow(data1)){
  if(min(data1[i,])<=-99){
    location<-which(data1[i,]==min(data1[i,]),arr.ind=TRUE)
    data1[i,location[,2]]<-NA
  } 
}
```

```{R}
#列均值插补缺失值得到data2
mu<-matrix(rep(colMeans(data1,na.rm = TRUE),nrow(data1)),byrow=TRUE,nrow=nrow(data1))
missing<-is.na(data1)
data2<-data1
data2[missing]<-mu[missing]
```

```{r}
#library("tseries")
#ts<-as.ts(data2[,2],frequency=12)
#adf.test(ts)
```

```{r}
data_tensor<-array(rep(0,ncol(data2)*nrow(data2)),dim=c(10,10,nrow(data2)))
for(t in 1:nrow(data2)){
  temp<-data2[t,]
  data_tensor[,,t]<-as.matrix(temp,nrow=10)
}
#生成的矩阵切片是B1,...,B10为行，M1,...,M10为列
```

## 缺失机制   

```{r}
MCAR<-function(X,rate){   #tensorX，维度为10*10*706，rate为缺失率
  d1<-dim(X)[1];d2<-dim(X)[2];Tx<-dim(X)[3]
  missnum<-floor(d1*d2*Tx*rate)   #总缺失数
  count_total<-0
  xindex<-sample(1:d1,size=d1)   #打乱x索引顺序
  for(x in xindex){
    miss<-sample(floor(d2*Tx*0.1):floor(d2*Tx*0.2),size=1)  
    #抽取这一x切片缺失数
    count_piece<-0
    if((count_total+miss)>missnum) {   #超出缺失数的情况
      miss<-missnum-count_total   #最后一个切片只缺失这么多
      yindex<-sample(floor(d2/2):d2,size=length(floor(d2/2):d2))    #打乱y索引
      for(y in yindex){
        missz<-sample((Tx*0.4):(Tx*0.5),size=1)
        if((count_piece+missz)>miss){
          missz<-miss-count_piece
          zindex<-sample(floor(Tx/2):Tx,size=missz)     #缺失z索引
          X[x,y,zindex]<-NA
          break
        }
        else{
          zindex<-sample(floor(Tx/2):Tx,size=missz)     #缺失z索引
          X[x,y,zindex]<-NA
        }
        count_piece<-count_piece+missz
      }
      break    #停止循环
    }
    else{
      yindex<-sample(floor(d2/2):d2,size=length(floor(d2/2):d2))    #打乱后半部分y索引
      for(y in yindex){
        missz<-sample((Tx*0.4):(Tx*0.5),size=1)
        if((count_piece+missz)>miss){
          missz<-miss-count_piece
          zindex<-sample(floor(Tx/2):Tx,size=missz)     #缺失z索引
          X[x,y,zindex]<-NA
          break
        }
        else{
          zindex<-sample(floor(Tx/2):Tx,size=missz)     #缺失z索引，集中在T大的部分
          X[x,y,zindex]<-NA
        }
        count_piece<-count_piece+missz
      }
     
    }
    count_total<-count_total+miss    #累计缺失数递增
  }
  return(X)
}
```   

## 算法实施函数  

```{r}
library("fbi")
Slicing_TW<-function(X,r,flag){   
  #flag=1即沿x轴切，flag=2即沿y轴切，flag=3沿z轴切
  #输入：X是有缺失值的矩阵，r是切片因子向量的维度，flag是沿何方向切片的标志
  #输出：返回插补后的tensor-X_imputed
  p<-dim(X)   #维度
  X_imputed<-array(rep(0,p[1]*p[2]*p[3]),dim=c(p[1],p[2],p[3]))
  if(flag==1){
    for(x in 1:p[1]){
      X_piece_x<-t(as.matrix(X[x,,]))   #Tx*p2
      out<-fbi::tw_apc(X_piece_x,kmax=r,center=FALSE,standardize = FALSE,re_estimate = TRUE)
      X_imputed[x,,]<-t(out$data)   #插补后的矩阵
    }
  }
  if(flag==2){
    for(y in 1:p[2]){
      X_piece_y<-t(as.matrix(X[,y,]))
      out<-fbi::tw_apc(X_piece_y,kmax=r,center=FALSE,standardize = FALSE,re_estimate = TRUE)
      X_imputed[,y,]<-t(out$data)   #插补后的矩阵
    }
  }
  if(flag==3){
    for(z in 1:p[3]){
      X_piece_z<-as.matrix(X[,,z])
      out<-fbi::tw_apc(X_piece_z,kmax=r,center=FALSE,standardize = FALSE,re_estimate = TRUE)
      X_imputed[,,z]<-out$data   #插补后的矩阵
    }
  }
  return(X_imputed)
}
```

## 评价指标    

这里评价指标取平均的平均数是缺失数据数目，考虑到X_hat只插补了缺失值。    

```{r}
MAE<-function(X_hat,X,rate){
  dimension<-dim(X)[1]*dim(X)[2]*dim(X)[3]
  missnum<-floor(dimension*rate)
  return(sum(abs(X_hat-X))/missnum)
}
```

## 数据补全   



```{r}
#初始值设定
repeats<-100 
mae<-matrix(rep(0,12),nrow=3,byrow=TRUE)
evaluation<-data.frame("dim"=c("(10,10,706)","(10,10,706)","(10,10,706)"),"missrate"=c("2.5%","5%","7.5%"),"all"=c(0,0,0),"x_piece"=c(0,0,0),"y_piece"=c(0,0,0),"z_piece"=c(0,0,0))
#模拟
#缺失2.5%
for(number in 1:repeats){
  #生成数据
  X_complete<-data_tensor
  X_miss<-MCAR(X_complete,0.025)
  
  #插补含缺失值的矩阵
  #切片p2p3
  X1<-Slicing_TW(X_miss,r=2,flag=1)
  #切片p1p3
  X2<-Slicing_TW(X_miss,r=2,flag=2)
  #切片p1p2
  X3<-Slicing_TW(X_miss,r=2,flag=3)

  #取均值作为插补估计值
  X_hat<-(X1+X2+X3)/3

  #计算误差指标
  mae[1,1]<-mae[1,1]+MAE(X_hat,X_complete,0.025)
  mae[1,2]<-mae[1,2]+MAE(X1,X_complete,0.025)
  mae[1,3]<-mae[1,3]+MAE(X2,X_complete,0.025)
  mae[1,4]<-mae[1,4]+MAE(X3,X_complete,0.025)
}

#缺失5%
for(number in 1:repeats){
  #生成数据
  X_complete<-data_tensor
  X_miss<-MCAR(X_complete,0.05)
  
  #插补含缺失值的矩阵
  #切片p2p3
  X1<-Slicing_TW(X_miss,r=2,flag=1)
  #切片p1p3
  X2<-Slicing_TW(X_miss,r=2,flag=2)
  #切片p1p2
  X3<-Slicing_TW(X_miss,r=2,flag=3)

  #取均值作为插补估计值
  X_hat<-(X1+X2+X3)/3

  #计算误差指标
  mae[2,1]<-mae[2,1]+MAE(X_hat,X_complete,0.05)
  mae[2,2]<-mae[2,2]+MAE(X1,X_complete,0.05)
  mae[2,3]<-mae[2,3]+MAE(X2,X_complete,0.05)
  mae[2,4]<-mae[2,4]+MAE(X3,X_complete,0.05)
}

#缺失7.5%
for(number in 1:repeats){
  #生成数据
  X_complete<-data_tensor
  X_miss<-MCAR(X_complete,0.075)
  
  #插补含缺失值的矩阵
  #切片p2p3
  X1<-Slicing_TW(X_miss,r=2,flag=1)
  #切片p1p3
  X2<-Slicing_TW(X_miss,r=2,flag=2)
  #切片p1p2
  X3<-Slicing_TW(X_miss,r=2,flag=3)

  #取均值作为插补估计值
  X_hat<-(X1+X2+X3)/3

  #计算误差指标
  mae[3,1]<-mae[3,1]+MAE(X_hat,X_complete,0.075)
  mae[3,2]<-mae[3,2]+MAE(X1,X_complete,0.075)
  mae[3,3]<-mae[3,3]+MAE(X2,X_complete,0.075)
  mae[3,4]<-mae[3,4]+MAE(X3,X_complete,0.075)
}

mae<-round(mae/repeats,4)
evaluation[1,3:6]<-mae[1,1:4]
evaluation[2,3:6]<-mae[2,1:4]
evaluation[3,3:6]<-mae[3,1:4]
cat("插补后的补全矩阵和原矩阵间MAE为","\n")
print(evaluation)
```